window.onAppReady(async () => {
    const db=window.supabaseClient, schoolId=window.currentSchoolId, PAGE_SIZE=25;
    const $=id=>document.getElementById(id), clean=v=>String(v??'').trim(), val=id=>clean($(id)?.value), num=id=>Math.max(0,Number($(id)?.value)||0);
    const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
    const money=v=>`Rs ${Math.round(Number(v)||0).toLocaleString()}`;
    const today=()=>{const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Karachi',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`;};
    const formatDate=v=>v?new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Karachi',day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${String(v).slice(0,10)}T12:00:00+05:00`)):'—';
    const can=action=>window.userRoleName==='super_admin'||!window.hasPermission||window.hasPermission('library_books',action);
    const suggestedCategories=['Literature','English','Urdu','Sindhi','Mathematics','Science','Computer Science','Islamiyat','Pakistan Studies','History','Geography','General Knowledge','Reference','Children','Other'];
    let books=[],categories=[],transactions=[],students=[],staff=[],enriched=[],loans=[],page=1,editingBookId=null,mode='ISSUE',relatedIssueId=null,categoryChart=null,statusChart=null;

    function toast(message,error=false){const e=$('toast');e.textContent=message;e.className=`toast show${error?' error':''}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.className='toast',3500);}
    function openModal(id){$(id).classList.add('open');$(id).setAttribute('aria-hidden','false');}
    function closeModal(id){$(id).classList.remove('open');$(id).setAttribute('aria-hidden','true');}
    async function fetchAll(table,columns='*',order='created_at'){
        const out=[];for(let from=0;;from+=1000){let q=db.from(table).select(columns).eq('school_id',schoolId);if(order)q=q.order(order,{ascending:true}).order('id',{ascending:true});q=q.range(from,from+999);const{data,error}=await q;if(error)throw error;out.push(...(data||[]));if(!data||data.length<1000)break;}return out;
    }
    async function optionalRows(table,columns){try{return await fetchAll(table,columns,'created_at');}catch(error){console.warn(`${table} lookup unavailable`,error);return[];}}

    function bookTransactions(id){return transactions.filter(t=>t.book_id===id).sort((a,b)=>String(a.transaction_date).localeCompare(String(b.transaction_date))||String(a.created_at).localeCompare(String(b.created_at)));}
    function computeBook(book){
        const rows=bookTransactions(book.id),state={available:0,issued:0,damaged:0,lost:0,withdrawn:0};let total=0,value=0,fines=0,repairs=0,loss=0;
        rows.forEach(t=>{const q=Number(t.quantity)||0;if(['ACQUIRE','ADD_COPIES'].includes(t.transaction_type)){total+=q;value+=q*(Number(t.unit_cost)||0);}if(t.source_bucket&&state[t.source_bucket]!==undefined)state[t.source_bucket]-=q;if(t.destination_bucket&&state[t.destination_bucket]!==undefined)state[t.destination_bucket]+=q;fines+=Number(t.fine_amount)||0;repairs+=Number(t.repair_cost)||0;loss+=Number(t.loss_amount)||0;});
        Object.keys(state).forEach(k=>state[k]=Math.max(0,state[k]));
        const categoryName=book.library_categories?.name||'Uncategorized', live=state.available+state.issued+state.damaged;
        const calculatedStatus=book.status==='Deleted'?'Deleted':(book.status==='Archived'||(total>0&&live===0)?'Archived':'Active');
        return{...book,rows,state,totalCopies:total,purchaseValue:value,unitCost:total?value/total:Number(book.purchase_price_per_copy)||0,fines,repairs,loss,categoryName,live,calculatedStatus};
    }
    function computeLoans(){
        const closures=new Map();transactions.filter(t=>['RETURN','RETURN_DAMAGED','LOST'].includes(t.transaction_type)&&t.related_issue_id).forEach(t=>closures.set(t.related_issue_id,(closures.get(t.related_issue_id)||0)+(Number(t.quantity)||0)));
        loans=transactions.filter(t=>t.transaction_type==='ISSUE').map(issue=>{const outstanding=Math.max(0,(Number(issue.quantity)||0)-(closures.get(issue.id)||0));const book=enriched.find(b=>b.id===issue.book_id);const overdue=outstanding>0&&issue.due_date<today();return{...issue,outstanding,book,overdue,dueToday:outstanding>0&&issue.due_date===today()};}).filter(x=>x.outstanding>0);
    }
    async function loadData(){
        if(!schoolId)throw new Error('School could not be identified.');
        try{[categories,books,transactions,students,staff]=await Promise.all([fetchAll('library_categories','*','name'),fetchAll('library_books','*, library_categories(name)','created_at'),fetchAll('library_book_transactions','*','created_at'),optionalRows('admissions','id,roll_number,full_name,father_mobile,father_whatsapp,applying_for_class,status,created_at'),optionalRows('staff','id,employee_id,full_name,mobile,whatsapp,job_title,status,created_at')]);$('setupWarning').style.display='none';enriched=books.map(computeBook);computeLoans();renderAll();}
        catch(error){console.error(error);if(error.code==='42P01'||/does not exist|schema cache|record_library_transaction/i.test(error.message||''))$('setupWarning').style.display='block';throw error;}
    }
    function renderAll(){populateLists();renderDashboard();renderCatalogue();renderLoans();renderHistory();renderCategories();}
    function populateLists(){
        const names=[...new Set([...suggestedCategories,...categories.map(c=>c.name)].filter(Boolean))].sort();$('categorySuggestions').innerHTML=names.map(n=>`<option value="${esc(n)}"></option>`).join('');$('categoryFilter').innerHTML='<option value="">All Categories</option>'+names.map(n=>`<option>${esc(n)}</option>`).join('');
        $('transactionBook').innerHTML='<option value="">Select book</option>'+enriched.filter(b=>b.calculatedStatus!=='Deleted').sort((a,b)=>a.title.localeCompare(b.title)).map(b=>`<option value="${b.id}">${esc(b.title)} — ${esc(b.accession_code||b.id.slice(0,8))}</option>`).join('');
    }
    function renderDashboard(){
        const active=enriched.filter(b=>b.calculatedStatus!=='Deleted'),t=active.reduce((s,b)=>{s.copies+=b.totalCopies;s.available+=b.state.available;s.issued+=b.state.issued;s.damaged+=b.state.damaged;s.lost+=b.state.lost;s.withdrawn+=b.state.withdrawn;s.value+=b.purchaseValue;s.fines+=b.fines;s.repairs+=b.repairs;s.loss+=b.loss;return s;},{copies:0,available:0,issued:0,damaged:0,lost:0,withdrawn:0,value:0,fines:0,repairs:0,loss:0});
        const cards=[['Book Titles',active.length,'fa-book',''],['Total Copies',t.copies,'fa-book-open',''],['Available',t.available,'fa-circle-check','green'],['Issued',t.issued,'fa-hand-holding',''],['Overdue',loans.filter(l=>l.overdue).reduce((s,l)=>s+l.outstanding,0),'fa-clock','red'],['Damaged',t.damaged,'fa-book-skull','red'],['Lost',t.lost,'fa-question','red'],['Withdrawn',t.withdrawn,'fa-box-archive',''],['Purchase Value',money(t.value),'fa-money-bill','green'],['Fines Recorded',money(t.fines),'fa-receipt','amber'],['Repair Expenses',money(t.repairs),'fa-screwdriver-wrench','amber'],['Recorded Loss',money(t.loss),'fa-arrow-trend-down','red']];
        $('libraryStats').innerHTML=cards.map(([l,v,i,c])=>`<article class="card ${c}"><span>${l}</span><strong>${typeof v==='number'?v.toLocaleString():v}</strong><i class="fas ${i}"></i></article>`).join('');drawCharts(active);
    }
    function drawCharts(active){if(!window.Chart)return;const cat={};active.forEach(b=>cat[b.categoryName]=(cat[b.categoryName]||0)+b.totalCopies);categoryChart?.destroy();categoryChart=new Chart($('categoryChart'),{type:'bar',data:{labels:Object.keys(cat),datasets:[{data:Object.values(cat),backgroundColor:'#8b5cf6',borderRadius:6}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true}}}});const s=active.reduce((x,b)=>{Object.keys(x).forEach(k=>x[k]+=b.state[k]);return x;},{available:0,issued:0,damaged:0,lost:0,withdrawn:0});statusChart?.destroy();statusChart=new Chart($('statusChart'),{type:'doughnut',data:{labels:['Available','Issued','Damaged','Lost','Withdrawn'],datasets:[{data:Object.values(s),backgroundColor:['#22c55e','#3b82f6','#ef4444','#7c3aed','#64748b']}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}});}
    function filteredBooks(){const search=val('bookSearch').toLowerCase(),cat=val('categoryFilter'),availability=val('availabilityFilter'),status=val('statusFilter'),sort=val('bookSort')||'title';const rows=enriched.filter(b=>{const hay=[b.title,b.author,b.isbn,b.accession_code,b.publisher,b.shelf_location,b.categoryName].join(' ').toLowerCase();return(!search||hay.includes(search))&&(!cat||b.categoryName===cat)&&(!availability||b.state[availability]>0)&&(!status||b.calculatedStatus===status);});rows.sort((a,b)=>sort==='available_desc'?b.state.available-a.state.available:sort==='issued_desc'?b.state.issued-a.state.issued:sort==='value_desc'?b.purchaseValue-a.purchaseValue:a.title.localeCompare(b.title,undefined,{numeric:true}));return rows;}
    function icon(action,id,fa,title,disabled=false){return`<button class="icon" data-action="${action}" data-id="${id}" title="${title}"${disabled?' disabled':''}><i class="fas ${fa}"></i></button>`;}
    function renderCatalogue(){const rows=filteredBooks(),pages=Math.max(1,Math.ceil(rows.length/PAGE_SIZE));page=Math.min(page,pages);const visible=rows.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);$('pageInfo').textContent=`Page ${page} of ${pages} · ${rows.length} titles`;$('prevPage').disabled=page<=1;$('nextPage').disabled=page>=pages;$('bookTableBody').innerHTML=visible.length?visible.map(b=>`<tr><td><strong>${esc(b.accession_code||`LIB-${b.id.slice(0,8).toUpperCase()}`)}</strong></td><td><span class="book">${esc(b.title)}</span><span class="sub">${esc(b.author||'Author not recorded')}</span></td><td>${esc(b.isbn||'—')}</td><td>${esc(b.categoryName)}</td><td>${esc(b.shelf_location||'—')}</td><td class="num">${b.totalCopies}</td><td class="num">${b.state.available}</td><td class="num">${b.state.issued}</td><td class="num">${b.state.damaged}</td><td class="num">${b.state.lost}</td><td class="num">${b.state.withdrawn}</td><td class="num">${money(b.purchaseValue)}</td><td><span class="badge ${b.calculatedStatus.toLowerCase()}">${b.calculatedStatus}</span></td><td><div class="actions">${icon('view',b.id,'fa-eye','View history')}${icon('edit',b.id,'fa-pen','Edit details',!can('can_edit'))}${icon('ADD_COPIES',b.id,'fa-plus','Add copies',!can('can_create'))}${icon('ISSUE',b.id,'fa-hand-holding','Issue book',b.state.available<1||!can('can_edit'))}${icon('DAMAGE',b.id,'fa-book-skull','Mark damaged',b.state.available<1||!can('can_edit'))}${icon('REPAIR',b.id,'fa-screwdriver-wrench','Mark repaired',b.state.damaged<1||!can('can_edit'))}${icon('LOST',b.id,'fa-question','Mark available copy lost',b.state.available<1||!can('can_edit'))}${icon('WITHDRAW',b.id,'fa-box-archive','Withdraw copy',b.state.available+b.state.damaged<1||!can('can_edit'))}${icon('delete',b.id,'fa-ban','Soft delete title',!can('can_delete'))}</div></td></tr>`).join(''):'<tr><td colspan="14" class="empty">No books match the filters.</td></tr>';}
    function filteredLoans(){const search=val('loanSearch').toLowerCase(),status=val('loanStatus');return loans.filter(l=>{const hay=[l.book?.title,l.borrower_name,l.borrower_number,l.borrower_class,l.borrower_mobile].join(' ').toLowerCase();return(!search||hay.includes(search))&&(!status||(status==='overdue'&&l.overdue)||(status==='due_today'&&l.dueToday));}).sort((a,b)=>String(a.due_date).localeCompare(String(b.due_date)));}
    function renderLoans(){$('loanTableBody').innerHTML=filteredLoans().length?filteredLoans().map(l=>`<tr><td><span class="book">${esc(l.book?.title||'Unknown')}</span></td><td>${esc(l.borrower_name||'—')}<span class="sub">${esc(l.borrower_type||'')}</span></td><td>${esc(l.borrower_number||'—')}</td><td>${esc(l.borrower_class||'—')}</td><td>${esc(l.borrower_mobile||'—')}</td><td>${formatDate(l.transaction_date)}</td><td>${formatDate(l.due_date)}</td><td class="num"><strong>${l.outstanding}</strong></td><td><span class="badge ${l.overdue?'overdue':'issued'}">${l.overdue?'Overdue':l.dueToday?'Due Today':'Issued'}</span></td><td>${esc(l.created_by_name||'—')}</td><td><div class="actions"><button class="btn success" data-loan-action="RETURN" data-id="${l.id}">Return</button><button class="btn amber" data-loan-action="RETURN_DAMAGED" data-id="${l.id}">Damaged</button><button class="btn danger" data-loan-action="LOST" data-id="${l.id}">Lost</button></div></td></tr>`).join(''):'<tr><td colspan="11" class="empty">No active issued books.</td></tr>';}
    function renderHistory(){const type=val('historyType');const rows=[...transactions].filter(t=>!type||t.transaction_type===type).sort((a,b)=>String(b.transaction_date).localeCompare(String(a.transaction_date))||String(b.created_at).localeCompare(String(a.created_at)));$('historyTableBody').innerHTML=rows.length?rows.map(t=>{const b=enriched.find(x=>x.id===t.book_id);return`<tr><td>${formatDate(t.transaction_date)}</td><td><span class="book">${esc(b?.title||'Unknown')}</span></td><td><span class="badge ${t.transaction_type.toLowerCase()}">${esc(t.transaction_type.replaceAll('_',' '))}</span></td><td class="num">${t.quantity}</td><td>${esc(t.borrower_name||'—')}<span class="sub">${esc(t.borrower_number||'')}</span></td><td>${t.return_date?formatDate(t.return_date):formatDate(t.due_date)}</td><td>${esc(t.reason||t.condition_note||t.notes||'—')}</td><td class="num">${money(t.fine_amount)}</td><td class="num">${money(t.repair_cost)}</td><td class="num">${money(t.loss_amount)}</td><td>${esc(t.created_by_name||'—')}</td></tr>`;}).join(''):'<tr><td colspan="11" class="empty">No transactions.</td></tr>';}
    function renderCategories(){$('categoryChips').innerHTML=categories.length?categories.map(c=>`<span class="chip"><i class="fas fa-tag"></i> ${esc(c.name)}</span>`).join(''):'<span class="sub">No saved categories yet. You may also type a category while adding a book.</span>';}

    function resetBookForm(){$('bookForm').reset();editingBookId=null;$('bookModalTitle').textContent='Add Library Book';$('bookQuantity').disabled=false;$('bookQuantity').closest('.form-group').style.display='';calcBookValue();}
    function calcBookValue(){$('bookTotalValue').textContent=money(num('bookQuantity')*num('bookUnitCost'));}
    async function ensureCategory(name){if(!name)return null;let found=categories.find(c=>c.name.toLowerCase()===name.toLowerCase());if(found)return found.id;const{data,error}=await db.from('library_categories').insert({school_id:schoolId,name}).select('id,name').single();if(error)throw error;categories.push(data);return data.id;}
    function bookPayload(categoryId){const p={school_id:schoolId,accession_code:val('bookCode')||null,isbn:val('bookIsbn')||null,title:val('bookTitle'),author:val('bookAuthor')||null,category_id:categoryId,publisher:val('bookPublisher')||null,edition:val('bookEdition')||null,language:val('bookLanguage')||null,shelf_location:val('bookShelf')||null,purchase_date:val('bookPurchaseDate')||null,purchase_price_per_copy:num('bookUnitCost'),supplier:val('bookSupplier')||null,invoice_number:val('bookInvoice')||null,notes:val('bookNotes')||null};if(window.campusFeatureReady&&window.currentCampusId)p.campus_id=window.currentCampusId;if(!editingBookId)p.created_by=window.currentUser?.id||null;return p;}
    async function record(params){const defaults={p_book_id:null,p_transaction_type:null,p_quantity:0,p_transaction_date:today(),p_source_bucket:null,p_destination_bucket:null,p_unit_cost:0,p_related_issue_id:null,p_borrower_type:null,p_borrower_id:null,p_borrower_name:null,p_borrower_number:null,p_borrower_class:null,p_borrower_mobile:null,p_due_date:null,p_return_date:null,p_condition_note:null,p_reason:null,p_fine_amount:0,p_repair_cost:0,p_loss_amount:0,p_notes:null,p_created_by_name:window.currentUserFullName||window.currentUser?.email||null};const{data,error}=await db.rpc('record_library_transaction',{...defaults,...params});if(error)throw error;return data;}
    async function saveBook(e){e.preventDefault();if(!can(editingBookId?'can_edit':'can_create'))return toast('You do not have permission.',true);const title=val('bookTitle'),qty=Math.floor(num('bookQuantity'));if(!title)return toast('Book Title is required.',true);if(!editingBookId&&qty<1)return toast('Quantity must be at least 1.',true);$('saveBook').disabled=true;try{const categoryId=await ensureCategory(val('bookCategory')),payload=bookPayload(categoryId);if(editingBookId){const{error}=await db.from('library_books').update(payload).eq('id',editingBookId).eq('school_id',schoolId);if(error)throw error;toast('Book details updated; copy totals were unchanged.');}else{const{data:book,error}=await db.from('library_books').insert(payload).select('id').single();if(error)throw error;try{await record({p_book_id:book.id,p_transaction_type:'ACQUIRE',p_quantity:qty,p_transaction_date:val('bookPurchaseDate')||today(),p_destination_bucket:'available',p_unit_cost:num('bookUnitCost'),p_reason:'Initial library acquisition',p_notes:val('bookNotes')||null});}catch(txError){await db.from('library_books').update({status:'Deleted',deleted_at:new Date().toISOString()}).eq('id',book.id).eq('school_id',schoolId);throw txError;}toast('Book and acquisition transaction saved.');}closeModal('bookModal');await loadData();}catch(error){console.error(error);toast(`Could not save book: ${error.message}`,true);}finally{$('saveBook').disabled=false;}}
    function editBook(id){const b=enriched.find(x=>x.id===id);if(!b)return;resetBookForm();editingBookId=id;$('bookModalTitle').textContent='Edit Book Details';const f={bookTitle:b.title,bookAuthor:b.author,bookCategory:b.categoryName==='Uncategorized'?'':b.categoryName,bookCode:b.accession_code,bookIsbn:b.isbn,bookShelf:b.shelf_location,bookPublisher:b.publisher,bookEdition:b.edition,bookLanguage:b.language,bookPurchaseDate:b.purchase_date,bookUnitCost:b.purchase_price_per_copy,bookSupplier:b.supplier,bookInvoice:b.invoice_number,bookNotes:b.notes};Object.entries(f).forEach(([id,v])=>$(id).value=v??'');$('bookQuantity').value=b.totalCopies;$('bookQuantity').disabled=true;$('bookQuantity').closest('.form-group').style.display='none';calcBookValue();openModal('bookModal');}

    const config={ADD_COPIES:{title:'Add Book Copies',source:null,dest:'available',show:['unitCostGroup']},ISSUE:{title:'Issue Library Book',source:'available',dest:'issued',show:['borrowerFields']},RETURN:{title:'Return Library Book',source:'issued',dest:'available',show:['fineGroup','conditionGroup']},RETURN_DAMAGED:{title:'Return Book as Damaged',source:'issued',dest:'damaged',show:['fineGroup','conditionGroup']},DAMAGE:{title:'Mark Book Damaged',source:'available',dest:'damaged',show:['conditionGroup']},REPAIR:{title:'Mark Book Repaired',source:'damaged',dest:'available',show:['repairCostGroup','conditionGroup']},LOST:{title:'Mark Book Lost',source:'available',dest:'lost',show:['sourceGroup','lossGroup']},WITHDRAW:{title:'Withdraw Book Copy',source:'available',dest:'withdrawn',show:['sourceGroup','conditionGroup']}};
    function plusDays(days){const d=new Date(`${today()}T12:00:00+05:00`);d.setDate(d.getDate()+days);const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return`${y}-${m}-${day}`;}
    function openTransaction(newMode,bookId='',issueId=null){mode=newMode;relatedIssueId=issueId;$('transactionForm').reset();$('borrowerName').dataset.id='';$('transactionDate').value=today();$('transactionDueDate').value=plusDays(14);$('transactionTitle').textContent=config[mode].title;document.querySelectorAll('#transactionForm .conditional').forEach(e=>e.classList.remove('show'));config[mode].show.forEach(id=>$(id)?.classList.add('show'));$('transactionBook').disabled=false;$('transactionBook').value=bookId;$('transactionSource').value=config[mode].source||'available';const loan=loans.find(l=>l.id===issueId);if(loan){$('transactionBook').value=loan.book_id;$('transactionBook').disabled=true;$('transactionQuantity').value=loan.outstanding;$('availabilityBox').textContent=`Borrower: ${loan.borrower_name||'—'} · Outstanding against this issue: ${loan.outstanding}`;if(mode==='LOST')$('transactionSource').value='issued';$('transactionLoss').value=Math.round((loan.book?.unitCost||0)*loan.outstanding);}else updateAvailability();openModal('transactionModal');}
    function updateAvailability(){const b=enriched.find(x=>x.id===val('transactionBook'));if(!b){$('availabilityBox').textContent='Select a book';return;}$('availabilityBox').textContent=`Available ${b.state.available} · Issued ${b.state.issued} · Damaged ${b.state.damaged} · Lost ${b.state.lost} · Withdrawn ${b.state.withdrawn}`;if(mode==='LOST')$('transactionLoss').value=Math.round(b.unitCost*Math.floor(num('transactionQuantity')));}
    function lookupBorrower(){const number=val('borrowerNumber'),type=val('borrowerType');if(!number)return;if(type==='Student'){const s=students.find(x=>String(x.roll_number).toLowerCase()===number.toLowerCase());if(s){$('borrowerName').value=s.full_name||'';$('borrowerClass').value=s.applying_for_class||'';$('borrowerMobile').value=s.father_whatsapp||s.father_mobile||'';$('borrowerName').dataset.id=s.id;}}else if(type==='Staff'){const s=staff.find(x=>String(x.employee_id).toLowerCase()===number.toLowerCase());if(s){$('borrowerName').value=s.full_name||'';$('borrowerClass').value=s.job_title||'';$('borrowerMobile').value=s.whatsapp||s.mobile||'';$('borrowerName').dataset.id=s.id;}}}
    async function saveTransaction(e){e.preventDefault();if(!can(mode==='ADD_COPIES'?'can_create':'can_edit'))return toast('You do not have permission.',true);const b=enriched.find(x=>x.id===val('transactionBook')),qty=Math.floor(num('transactionQuantity')),cfg=config[mode];if(!b||qty<1)return toast('Select a book and valid quantity.',true);let source=cfg.source;if(['LOST','WITHDRAW'].includes(mode)&&!relatedIssueId)source=val('transactionSource')||'available';if(mode==='LOST'&&relatedIssueId)source='issued';const available=source?b.state[source]:Infinity;if(qty>available)return toast(`Only ${available} copy/copies are in ${source}.`,true);const loan=loans.find(l=>l.id===relatedIssueId);if(loan&&qty>loan.outstanding)return toast(`Only ${loan.outstanding} remain against this issue.`,true);if(mode==='ISSUE'&&(!val('borrowerName')||!val('transactionDueDate')))return toast('Borrower name and due date are required.',true);$('saveTransaction').disabled=true;try{await record({p_book_id:b.id,p_transaction_type:mode,p_quantity:qty,p_transaction_date:val('transactionDate')||today(),p_source_bucket:source,p_destination_bucket:cfg.dest,p_unit_cost:num('transactionUnitCost'),p_related_issue_id:relatedIssueId,p_borrower_type:mode==='ISSUE'?val('borrowerType'):loan?.borrower_type||null,p_borrower_id:mode==='ISSUE'?($('borrowerName').dataset.id||null):loan?.borrower_id||null,p_borrower_name:mode==='ISSUE'?val('borrowerName'):loan?.borrower_name||null,p_borrower_number:mode==='ISSUE'?val('borrowerNumber'):loan?.borrower_number||null,p_borrower_class:mode==='ISSUE'?val('borrowerClass'):loan?.borrower_class||null,p_borrower_mobile:mode==='ISSUE'?val('borrowerMobile'):loan?.borrower_mobile||null,p_due_date:mode==='ISSUE'?val('transactionDueDate'):loan?.due_date||null,p_return_date:['RETURN','RETURN_DAMAGED'].includes(mode)?val('transactionDate')||today():null,p_condition_note:val('transactionCondition')||null,p_reason:val('transactionReason')||null,p_fine_amount:num('transactionFine'),p_repair_cost:num('transactionRepairCost'),p_loss_amount:num('transactionLoss'),p_notes:val('transactionNotes')||null});closeModal('transactionModal');toast(`${cfg.title} saved to permanent history.`);await loadData();}catch(error){console.error(error);toast(`Transaction failed: ${error.message}`,true);}finally{$('saveTransaction').disabled=false;$('transactionBook').disabled=false;}}

    function describe(t){const labels={ACQUIRE:'Acquired',ADD_COPIES:'Copies added',ISSUE:'Issued',RETURN:'Returned',RETURN_DAMAGED:'Returned damaged',DAMAGE:'Marked damaged',REPAIR:'Repaired',LOST:'Marked lost',WITHDRAW:'Withdrawn'};return{label:labels[t.transaction_type]||t.transaction_type,details:[t.borrower_name,t.borrower_number,t.reason,t.condition_note,t.due_date?`Due ${formatDate(t.due_date)}`:null,t.fine_amount?`Fine ${money(t.fine_amount)}`:null,t.repair_cost?`Repair ${money(t.repair_cost)}`:null,t.loss_amount?`Loss ${money(t.loss_amount)}`:null,t.notes].filter(Boolean).join(' · ')};}
    function viewBook(id){const b=enriched.find(x=>x.id===id);if(!b)return;$('detailTitle').textContent=`${b.title} — Complete History`;const cards=[['Book Code',b.accession_code||`LIB-${b.id.slice(0,8).toUpperCase()}`],['Author',b.author||'—'],['ISBN',b.isbn||'—'],['Category',b.categoryName],['Shelf',b.shelf_location||'—'],['Total Copies',b.totalCopies],['Available',b.state.available],['Issued',b.state.issued],['Damaged',b.state.damaged],['Lost',b.state.lost],['Withdrawn',b.state.withdrawn],['Purchase Value',money(b.purchaseValue)],['Fines',money(b.fines)],['Repair Expenses',money(b.repairs)],['Recorded Loss',money(b.loss)]];const timeline=[...b.rows].reverse().map(t=>{const d=describe(t);return`<div class="event"><h4>${esc(d.label)} — ${t.quantity} copy/copies</h4><p>${formatDate(t.transaction_date)}${t.created_by_name?` · ${esc(t.created_by_name)}`:''}</p>${d.details?`<p>${esc(d.details)}</p>`:''}</div>`;}).join('');$('detailBody').innerHTML=`<div class="detail-grid">${cards.map(([l,v])=>`<div class="detail-card"><span>${l}</span><strong>${esc(v)}</strong></div>`).join('')}</div><div class="timeline">${timeline||'<p class="empty">No history.</p>'}</div>`;openModal('detailModal');}
    async function softDelete(id){if(!can('can_delete'))return toast('You do not have delete permission.',true);const b=enriched.find(x=>x.id===id);if(!b)return;if(b.state.issued>0)return toast('Return or close all issued copies before deleting this title.',true);if(!confirm(`Hide ${b.title}? All acquisition and circulation history will remain saved.`))return;const{error}=await db.from('library_books').update({status:'Deleted',deleted_at:new Date().toISOString()}).eq('id',id).eq('school_id',schoolId);if(error)return toast(error.message,true);toast('Book title soft-deleted; history preserved.');await loadData();}
    async function addCategory(e){e.preventDefault();if(!can('can_create'))return toast('You do not have permission.',true);try{await ensureCategory(val('newCategory'));$('categoryForm').reset();toast('Library category added.');await loadData();}catch(error){toast(error.message,true);}}
    function exportCsv(headers,rows,name){const q=x=>`"${String(x??'').replaceAll('"','""')}"`,csv='\uFEFF'+[headers,...rows].map(r=>r.map(q).join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`${name}-${today()}.csv`;a.click();URL.revokeObjectURL(url);}
    function exportCatalogue(){const rows=filteredBooks().map(b=>[b.accession_code||`LIB-${b.id.slice(0,8).toUpperCase()}`,b.title,b.author,b.isbn,b.categoryName,b.shelf_location,b.totalCopies,b.state.available,b.state.issued,b.state.damaged,b.state.lost,b.state.withdrawn,Math.round(b.purchaseValue)]);exportCsv(['Book ID','Title','Author','ISBN','Category','Shelf','Total','Available','Issued','Damaged','Lost','Withdrawn','Purchase Value'],rows,'Library-Book-Register');}
    function exportLoans(){const rows=filteredLoans().map(l=>[l.book?.title,l.borrower_name,l.borrower_type,l.borrower_number,l.borrower_class,l.borrower_mobile,l.transaction_date,l.due_date,l.outstanding,l.overdue?'Overdue':'Issued']);exportCsv(['Book','Borrower','Type','Roll/ID','Class/Dept','Mobile','Issue Date','Due Date','Outstanding','Status'],rows,'Library-Active-Loans');}
    function exportHistory(){const type=val('historyType'),rows=transactions.filter(t=>!type||t.transaction_type===type).map(t=>{const b=enriched.find(x=>x.id===t.book_id);return[t.transaction_date,b?.title,t.transaction_type,t.quantity,t.borrower_name,t.borrower_number,t.due_date,t.return_date,t.reason||t.condition_note,t.fine_amount,t.repair_cost,t.loss_amount,t.created_by_name];});exportCsv(['Date','Book','Transaction','Qty','Borrower','Roll/ID','Due','Return','Reason/Condition','Fine','Repair','Loss','By'],rows,'Library-History');}

    document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.panel-tab').forEach(x=>x.classList.toggle('active',x.id===btn.dataset.tab));}));document.querySelectorAll('[data-close]').forEach(btn=>btn.addEventListener('click',()=>closeModal(btn.dataset.close)));document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id);}));
    $('addBookBtn').addEventListener('click',()=>{resetBookForm();openModal('bookModal');});$('bookForm').addEventListener('submit',saveBook);$('bookQuantity').addEventListener('input',calcBookValue);$('bookUnitCost').addEventListener('input',calcBookValue);$('transactionForm').addEventListener('submit',saveTransaction);$('transactionBook').addEventListener('change',updateAvailability);$('transactionQuantity').addEventListener('input',updateAvailability);$('borrowerNumber').addEventListener('change',lookupBorrower);$('borrowerType').addEventListener('change',()=>{$('borrowerName').dataset.id='';lookupBorrower();});
    document.querySelectorAll('[data-new-mode]').forEach(btn=>btn.addEventListener('click',()=>openTransaction(btn.dataset.newMode)));$('bookTableBody').addEventListener('click',e=>{const btn=e.target.closest('[data-action]');if(!btn||btn.disabled)return;const{action,id}=btn.dataset;if(action==='view')viewBook(id);else if(action==='edit')editBook(id);else if(action==='delete')softDelete(id);else openTransaction(action,id);});$('loanTableBody').addEventListener('click',e=>{const btn=e.target.closest('[data-loan-action]');if(!btn)return;const loan=loans.find(l=>l.id===btn.dataset.id);if(loan)openTransaction(btn.dataset.loanAction,loan.book_id,loan.id);});
    ['bookSearch','categoryFilter','availabilityFilter','statusFilter','bookSort'].forEach(id=>$(id).addEventListener(id==='bookSearch'?'input':'change',()=>{page=1;renderCatalogue();}));$('loanSearch').addEventListener('input',renderLoans);$('loanStatus').addEventListener('change',renderLoans);$('historyType').addEventListener('change',renderHistory);$('prevPage').addEventListener('click',()=>{if(page>1){page--;renderCatalogue();}});$('nextPage').addEventListener('click',()=>{page++;renderCatalogue();});$('categoryForm').addEventListener('submit',addCategory);$('printCatalogue').addEventListener('click',()=>window.print());$('printHistory').addEventListener('click',()=>window.print());$('exportCatalogue').addEventListener('click',exportCatalogue);$('exportLoans').addEventListener('click',exportLoans);$('exportHistory').addEventListener('click',exportHistory);
    if(!can('can_create'))$('addBookBtn').disabled=true;
    try{await loadData();}catch(error){toast(`Library could not load: ${error.message}`,true);}
});
